apiVersion: apps/v1
kind: Deployment
metadata:
  name: osgvo-docker-pilot
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: osgvo-docker-pilot
          image: hub.opensciencegrid.org/opensciencegrid/osgvo-docker-pilot:testing-20210827-1744
          resources:
            limits:
              memory: "14Gi"
              cpu: "3.35"
          env:
            - name: GLIDEIN_ResourceName
              value: "RABBIT-OSG-BACKFILL-PROD"
            - name: GLIDEIN_Start_Extra
              value: 'ProjectName == "TG-CHE200122"'
            - name: NUM_CPUS
              value: "4"
            - name: MEMORY
              value: "14000"
            - name: CVMFSEXEC_REPOS
              value: "oasis.opensciencegrid.org singularity.opensciencegrid.org"
