apiVersion: apps/v1
kind: Deployment
metadata:
  name: osgvo-docker-pilot
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: osgvo-docker-pilot
          image: hub.opensciencegrid.org/opensciencegrid/osgvo-docker-pilot:testing-20210827-1744
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          env:
            - name: GLIDEIN_ResourceName
              value: "RABBIT-OSG-BACKFILL-PROD"
            - name: GLIDEIN_Start_Extra
              value: 'ProjectName == "TG-CHE200122"'
            - name: NUM_CPUS
              value: "2"
            - name: MEMORY
              value: "2000"
