apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: osgvo-docker-pilot
spec:
  podSelector:
    matchLabels:
      app: "osgvo-docker-pilot"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: "traefik"
# Needs access to open pool cm and schedds
  egress:
  - {}
